Repository uniwhales/component-library, pull requests merged in 2022-11, with the labels that each got.

#117 Fe 561 changing the cursor after hovering over following
  package.json
  src/organisms/navbar/styles.tsx
Labels: bug

#116 Fe 521
  package.json
  src/atoms/buttons/button.stories.tsx
  src/atoms/buttons/button.tsx
  src/atoms/buttons/types.ts
  src/atoms/chips/chip.styles.ts
  src/atoms/chips/filterChip.tsx
  src/atoms/icons/generalIcons/filledStyle/ActivityStandard.tsx
  src/atoms/icons/generalIcons/filledStyle/FetchError.tsx
  src/atoms/icons/generalIcons/filledStyle/Hide.tsx
  src/atoms/icons/generalIcons/filledStyle/HoldersStandard.tsx
  src/atoms/icons/generalIcons/filledStyle/LoadError.tsx
  src/atoms/icons/iconWrapper.stories.tsx
  src/atoms/icons/iconWrapper.tsx
  src/atoms/icons/index.ts
  src/atoms/icons/types.ts
  src/atoms/inputs/checkbox.tsx
  src/atoms/inputs/select.tsx
  src/atoms/modal/modal.tsx
  src/molecules/copyToClipBoard/copyToClipBoard.stories.tsx
  src/molecules/copyToClipBoard/copyToClipBoard.tsx
  src/molecules/stickyActionBar/stickyActionBar.tsx
  src/organisms/navbar/navbar.stories.tsx
  src/organisms/navbar/navbar.tsx
  src/organisms/navbar/styles.tsx
  src/utils/constants.ts
Labels: bug, enhancement

#118 adding nft root icon
  package.json
  src/atoms/icons/generalIcons/filledStyle/NftSidebarStandard.tsx
  src/atoms/icons/iconWrapper.stories.tsx
  src/atoms/icons/index.ts
Labels: enhancement

#119 Fe 558 special small button updates
  package.json
  src/atoms/buttons/button.stories.tsx
  src/atoms/buttons/button.tsx
  src/atoms/buttons/types.ts
Labels: bug, enhancement

#121 Fe 567/582/587 modals and messaging
  package.json
  src/atoms/inputs/input.stories.tsx
  src/atoms/inputs/input.tsx
  src/atoms/inputs/select.tsx
  src/atoms/modal/modal.stories.tsx
  src/atoms/modal/modal.tsx
  src/atoms/modal/modalModel.tsx
  src/atoms/modal/styles.ts
  src/atoms/modal/types.ts
  src/atoms/socialButtonGroup/SocialButtonGroup.tsx
  src/atoms/socialButtonGroup/style.ts
  src/atoms/socialButtonGroup/types.ts
  src/index.ts
  src/molecules/dashboardMessages/DashMessageOne.tsx
  src/molecules/dashboardMessages/DashMessageTwo.tsx
  src/molecules/dashboardMessages/dashMessageOne.stories.tsx
  src/molecules/dashboardMessages/dashMessageTwo.stories.tsx
  src/molecules/dashboardMessages/style.ts
  src/molecules/dashboardMessages/types.ts
Labels: enhancement

#122 Fe 521
  package.json
  src/atoms/inputs/select.stories.tsx
  src/atoms/inputs/select.tsx
  src/atoms/navigationTab/navigationTab.tsx
  src/atoms/navigationTab/styles.tsx
  src/atoms/navigationTab/types.ts
  src/atoms/tags/tag.styles.ts
  src/molecules/hoverCard/hoverCard.stories.tsx
  src/molecules/hoverCard/hoverCard.tsx
  src/molecules/meatballMenu/meatballMenu.styles.ts
  src/organisms/hintsAndHovers/hintsAndHovers.tsx
  src/utils/useOnSwipe.ts
Labels: bug

#125 Add additional action to modal header
  package.json
  src/atoms/modal/modal.tsx
  src/atoms/modal/modalModel.tsx
  src/atoms/modal/styles.ts
  src/atoms/modal/types.ts
Labels: enhancement

#128 Portal modal tweaks
  package.json
  src/molecules/modals/modal.stories.tsx
  src/molecules/modals/modal.styles.ts
  src/molecules/modals/modal.tsx
  src/molecules/modals/types.ts
Labels: bug

#130 Input and modal props tweaks
  package.json
  src/atoms/inputs/input.tsx
  src/atoms/modal/modal.tsx
  src/atoms/modal/styles.ts
  src/atoms/modal/types.ts
  src/molecules/modals/modal.stories.tsx
  src/molecules/modals/modal.styles.ts
  src/molecules/modals/modal.tsx
  src/molecules/modals/types.ts
Labels: enhancement

#133 Fe 588
  package.json
  src/atoms/chips/filterChip.stories.tsx
  src/atoms/chips/filterChip.styles.ts
  src/atoms/chips/filterChip.tsx
  src/atoms/icons/types.ts
  src/atoms/identicon/Identicon.stories.tsx
  src/atoms/identicon/Identicon.styles.ts
  src/atoms/identicon/Identicon.tsx
  src/atoms/identicon/MarkedIdenticon.tsx
  src/atoms/identicon/SelectIdenticon.tsx
  src/atoms/identicon/SelectMarkedIdenticon.tsx
  src/atoms/identicon/types.ts
  src/atoms/inputs/checkbox.tsx
  src/index.ts
  src/organisms/navbar/navbar.stories.tsx
  src/organisms/navbar/navbar.tsx
  src/utils/getSize.ts
Labels: bug, enhancement
